config/routes.rb
Rails.application.routes.draw do
  resources 'sounds'
  root 'sounds#index'
  devise_for :users
end

app/models/sound.rb
class Sound < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sounds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, except: [:index, :create, :new]

  def index
    @sounds = Sound.all
    @public_sounds = Sound.where(public: :true)
  end

  def show
    @sound = Sound.find(params[:id])
  end

  def edit
  end

  def new
    @sound = Sound.new
    render 'show'
  end

  def create
    @sound = Sound.new(sound_params)
    respond_to do |format|
      if @sound.save
        format.html { redirect_to @sound, notice: 'Sound was successfully created.' }
        format.js do
          @sounds = Sound.all
          redirect_to @sound
        end
      else
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @sound.update(sound_params)
        format.js
        format.html { redirect_to @sound }
        format.json { render :show, status: :ok, location: @sound }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_sound
    @sound = Sound.find(params[:id])
  end

  def sound_params
    params.require(:sound).permit(:title, :code, :description, :user_id, :public)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "SynthSandbox" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
      <h1><%= link_to "SynthSandbox", root_path %></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
      <a href="#">Account</a>
      <ul class="dropdown">
        <% if current_user %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% if current_user.sounds.first %>
            <li><a href="#" data-reveal-id="mysoundsModal">Sounds</a></li>
          <% end %>
        <% else %>
          <li><a href="#" data-reveal-id="loginModal">Log In</a></li>
        <% end %>
      </ul>
      </li>
    </ul>
    <ul class="left">
      <li><%= link_to "Create", new_sound_path%></li>
    </ul>
    </section>
    </nav>
    <div class="large-6 columns large-centered">
      <% if notice %>
        <div data-alert class="alert-box info radius">
          <%= notice %>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>
      <% if alert %>
        <div data-alert class="alert-box alert radius">
          <%= alert %>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>
    </div>

    <%= yield %>

    <div id="loginModal" class="reveal-modal" data-reveal>
      <%= render '/sounds/login' %>
    </div>

    <% if current_user %>
      <div id="mysoundsModal" class="reveal-modal" data-reveal>
        <%= render partial: '/sounds/sound', collection: current_user.sounds %>
      </div>
    <% end %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/sounds/_buttons.html.erb
<ul class="button-group round">
  <li onclick="save()"><a href="#" data-reveal-id="saveModal", class="button tiny">Save</a></li>
  <li class="button tiny play-button" onclick="playCode()">Play</li>
  <li class="button tiny stop-button" onclick="stopCode()">Stop</li>
</ul>

app/views/sounds/_form.html.erb
<%= form_for(@sound, remote: true) do |f| %>
  <%= f.text_area :code, size: "60x12" %>
  <%= f.text_area :description, size: "60x12" %>
  <%= f.hidden_field :user_id, value: 10 %>
  <%= f.submit %>
<% end %>

app/views/sounds/_login.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in' %>
  <%= link_to "Don't have an account?", new_user_registration_path %>
<% end %>

app/views/sounds/_save.html.erb
<%= form_for @sound do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label "Would you like other users to be able to see your code?" %>
  <%= f.check_box :public %>
  <% if current_user %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>
  <%= f.hidden_field :code %>
  <%= f.hidden_field :description %>
  <%= f.submit 'Save', class: 'button tiny save-button' %>
<% end %>

<script>
  function save(){
    window.cmCode.save();
    window.cmDesc.save();
    var c = $("#codeText").val();
    $("#sound_code").val(c);
    var d = $("#descriptionText").val();
    $("#sound_description").val(d);
  }
</script>

app/views/sounds/_sound.html.erb
<div class="row">
  <div class="sounds">
    <% if sound.title %>
      <%= link_to "#{sound.title}", sound %>
    <% else %>
      <%= link_to "Sound #{sound.id}", sound %>
    <% end %>
    <hr>
  </div>
</div>

app/views/sounds/edit.html.erb
<%= render 'form' %>

app/views/sounds/index.html.erb
<div class="large-10 large-offset-1 columns">
  <h4>Welcome to SynthSandbox</h4>
  <p>Synth Sandbox is a creative environment for experimenting with audio synthesis.  The links below will take you to examples created by other users.  Everyone is encouraged to edit the code and save their own version.</p>
  <p>For more information about timbre.js, please visit this <%= link_to "link", "https://mohayonao.github.io/timbre.js/" %>.</p>
  <p>Note: If you are experiencing playback issues, try saving your code or refreshing the page.</p>
</div>

<hr>

<div>
  <%= render partial: '/sounds/sound', collection: @public_sounds %>
</div>

app/views/sounds/new.html.erb
<%= render 'form' %>

app/views/sounds/show.html.erb
<div class="container">
  <div class="large-6 columns text">
    <h4>Code</h4>
    <%= text_area(:sound, :code, cols:20, rows: 20, id: "codeText")%>
  </div>
  <div class="large-6 columns text">
    <h4>Description</h4>
    <%= text_area(:sound, :description, cols:20, rows: 20, id: "descriptionText")%>
  </div>

  <div class="buttons">
    <%= render 'buttons' %>
  </div>

  <div id="saveModal" class="reveal-modal" data-reveal>
    <% if current_user == @sound.user %>
      <%= render 'save' %>
    <% else %>
      <% @sound = Sound.new %>
      <%= render 'save' %>
    <% end %>
  </div>
</div>
<script>
  function playCode(){
    window.cmCode.save();
    var code = $("#codeText").val();
    console.log(code);
    eval(code);
  }

  function stopCode(){
    T.pause();
  }
</script>